### PR TITLE
Add automatic HAM (false positive) reporting based on user rep

### PR DESCRIPTION
**Pull request by lots0logs**
@akhoury Let me know if you see any issues. I was in a hurry when I wrote it :grimacing:

### CODE REVIEW

**Comment by akhoury** [comment]
@lots0logs thanks for this, but the diff is really hard to see with the all the spaces/tabbing changes.

**Comment by lots0logs** [comment]
These are the commits that have the important changes:
* https://github.com/lots0logs/nodebb-plugin-spam-be-gone/commit/ecb74f32a4c84e0ee23f4f2bcf815e3a315ae78c
* https://github.com/lots0logs/nodebb-plugin-spam-be-gone/commit/d2fd85463d980d030763add5fb1ee784b993d872

I can split this up if you want, but I can't do it until tonight (I'm working all day). Sorry!

**Comment by julianlam** [comment]
Just a note: We don't enforce coding style on plugins, even if they're bundled in with every NodeBB install. :smile:

If you guys order four spaces, all the power to you.

**Comment by lots0logs** [comment]
Well personally, I prefer tabs but that wasn't why I did it here (its not my plugin after all!). The `.editorconfig` file in this repo calls for tabs so that's why I did it. @akhoury Let me know if you prefer spaces, I can revert that part of the PR when I get home from work tonight. Cheers!

**Comment by akhoury** [comment]
> `.editorconfig` file in this repo calls for tabs so that's why I did it

oops my bad

>  Let me know if you prefer spaces

nah, i don't care, as long as we're consistent. Thanks for sharing the important commits, they look good.

**Pull request merged**
